- name: Set project directory variable
  set_fact:
    main_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/lab.nextcloud"

- name: Display project directory variable
  debug:
    msg: "Home Directory: {{ main_dir }}"

- name: Create virtual environment
  pip:
    name:
      - pyyaml
      - python-dotenv
    virtualenv: "{{ main_dir }}/env"

- name: Run pre-deployment.py
  command: "{{ main_dir }}/env/bin/python pre-infrastructure.py"
  args:
    chdir: "{{ main_dir }}"
  register: script_output
