- name: Check current VPN connection
  command: nmcli con show --active
  register: vpn_status

- name: Debug VPN status
  debug:
    msg: "{{ vpn_status.stdout }}"

- name: Connect to VPN if not connected
  command: wg-quick up {{ vpn_name }}
  when: vpn_name not in vpn_status.stdout

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "{{ ssh_path }}"
    type: rsa
    size: 4096
    state: present
    force: no
