---
- name: Set var project dir
  set_fact:
    main_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/lab.nextcloud"

- name: Report var
  debug:
    msg: "Home Directory: {{ main_dir }}"

- name: Run pre-application.py
  command: "{{ main_dir }}/env/bin/python {{ main_dir }}/pre-application.py"
  args:
    chdir: "{{ main_dir }}"
  register: script_output

- name: Report var
  debug:
    msg: "{{  script_output.stdout }}"

- name: Refresh inventory to load new configuration
  meta: refresh_inventory
