[bastion]
bs ansible_host=198.18.2.142 ansible_user=ubuntu

[webserver]
web ansible_host=192.168.94.10 ansible_user=ubuntu ansible_ssh_port=22

[all:vars]
ansible_ssh_private_key_file=/home/shl/.ssh/nc-ssh.pub
