[bastion]
bs ansible_host= ansible_user=ubuntu

[load_balancer]
lb ansible_host= ansible_user=ubuntu ansible_ssh_port=22

[database]
db ansible_host= ansible_user=ubuntu ansible_ssh_port=22

[webservers]
web-1 ansible_host= ansible_user=ubuntu ansible_ssh_port=22
web-2 ansible_host= ansible_user=ubuntu ansible_ssh_port=22

[all:vars]
ansible_ssh_private_key_file=
