---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install apache2
  apt:
    name: apache2
    state: latest
    update_cache: true

- name: Install required system packages
  apt:
    pkg:
      - php
      - php-common
      - libapache2-mod-php
      - php-bcmath
      - php-bz2
      - php-gd
      - php-curl
      - php-intl
      - php-gmp
      - php-json
      - php-pgsql
      - php-mbstring
      - php-imagick
      - php-xml
      - php-zip
      - zip
      - unzip
      - wget
    state: latest
    update_cache: true

- name: Enable Apache modules
  ansible.builtin.command: a2enmod env rewrite dir mime headers setenvif ssl

- name: Restart apache
  service:
    name: apache2
    state: restarted

- name: Remove index
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Download zip
  ansible.builtin.get_url:
    url: https://download.nextcloud.com/server/releases/latest.zip
    dest: /home/ubuntu/latest.zip

- name: Unzip Nextcloud
  ansible.builtin.unarchive:
    src: /home/ubuntu/latest.zip
    dest: /home/ubuntu/
    creates: /home/ubuntu/nextcloud
    remote_src: yes
    owner: www-data
    group: www-data
    mode: "0755"

- name: Copy Nextcloud
  copy:
    src: /home/ubuntu/nextcloud
    dest: /var/www/html
    remote_src: yes
    owner: www-data
    group: www-data
    mode: "0755"

- name: Copy PostgreSQL PHP configuration
  copy:
    src: pgsql.ini
    dest: /etc/php/8.1/cli/conf.d/pgsql.ini

- name: Ensure the config directory exists
  ansible.builtin.file:
    path: /var/www/html/config
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Update Nextcloud configuration
  template:
    src: config.php.j2
    dest: /var/www/html/config/config.php
    owner: www-data
    group: www-data
    mode: "0644"

- name: Restart Apache service
  service:
    name: apache2
    state: restarted
